apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: test-argotlsupdate-feb19-2
  janus-idp.io/tekton: test-argotlsupdate-feb19-2
  backstage.io/kubernetes-id: test-argotlsupdate-feb19-2
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: test-argotlsupdate-feb19-2
resources:
  - application-dev.yaml
