apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-argotlsupdate-feb19-2-gitops
  description: This is GitOps manifest for test-argotlsupdate-feb19-2   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=test-argotlsupdate-feb19-2
    janus-idp.io/tekton: test-argotlsupdate-feb19-2 
    backstage.io/kubernetes-id: test-argotlsupdate-feb19-2 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:test-argotlsupdate-feb19-2  
